### ISSUE TITLE
Melhorar mensagem de erro

### ISSUE THREAD

**Issue by dlibanori** [vindi/vindi-ruby#1]
Quando `Vindi::Client.new` tem os parâmetros nulos, o erro que dá é apenas um exceção com `+` no meio da biblioteca http. Seria legal lançar uma exceção na chamada de `new`

**Comment by carolina-y** [comment]
@dlibanori o PR #3 deve resolver da mesma forma. Você pode criar um caller com `Vindi::Client.new` e ele retorna um objeto novo. O erro com apenas a exceção acontecia porque não se tinha acesso à real mensagem de erro do servidor: agora ele retornará com uma mensagem como, por exemplo:

`Vindi::Error::Unauthorized: {"errors":[{"id":"unauthorized","parameter":"authorization","message":"Chave da API inválida"}]}`

* o servidor apenas faz a conexão quando chamando um método que o requeira, como `list_customers`.
