### ISSUE TITLE
Novo release

### ISSUE THREAD

**Issue by rainerborene** [vindi/vindi-ruby#17]
@laerte-guimaraes Pode fazer o novo release da versão `0.0.6` no Rubygems?

**Comment by rainerborene** [comment]
ping @wagner

**Comment by laerte-guimaraes** [comment]
Olá @rainerborene tudo bem?

Desculpe a demora.

A nova versão já se encontra disponível no [RubyGems](https://rubygems.org/gems/vindi)

Qualquer dúvida, estamos à disposição!

**Comment by rainerborene** [comment]
Valeu!
