### ISSUE TITLE
Melhorar erros nos métodos em geral

### ISSUE THREAD

**Issue by dlibanori** [vindi/vindi-ruby#2]
Quando alguma operação falha o erro é apenas um 422 cabendo ao desenvolvedor _caçar_ qual o campo que deu problema

**Comment by brunoadacosta** [comment]
@dlibanori vou investigar, obrigado

**Comment by carolina-y** [comment]
@dlibanori o PR #3 deve resolver. Pode revisar, por favor?

**Comment by dlibanori** [comment]
@carolina-y conheço pouco do retorno direto do _Rest_ de vocês e presumi que o body contém a mensagem de erro. Revisado
