### ISSUE TITLE
(chore) Upgrade Faraday to v1.0

### ISSUE THREAD

**Issue by giovannibonetti** [vindi/vindi-ruby#22]
A gem Faraday teve [uma atualização do tipo _major_ em janeiro](https://github.com/lostisland/faraday/releases/tag/v1.0.0) e [algumas outras _gems_ como a do Sentry já fizeram o _upgrade_](https://github.com/getsentry/raven-ruby/pull/946). Daí precisamos que a _gem_ da Vindi seja atualizada para o Faraday 1.0 também para poder atualizar tudo.

Na [documentação do Faraday](https://github.com/lostisland/faraday/blob/master/UPGRADING.md) há instruções para o Upgrade.

Obrigado.

**Comment by laerte-guimaraes** [comment]
Atualizado na versão [0.0.9](https://github.com/vindi/vindi-ruby/releases/tag/v0.0.9)
