### ISSUE TITLE
Colocar instruções de como utilizar o sandbox

### ISSUE THREAD

**Issue by dlibanori** [vindi/vindi-ruby#4]
Faltam instruções de como alterar o endpoint para utilizar o sandbox. Isto é bem importante pois todo desenvolvimento começa pelo uso do sandbox. Eu tive de abrir o código para ver como configurar. Não foi algo difícil, mas poderia ser mais simples se estivesse no README

**Comment by rainerborene** [comment]
@laerte-guimaraes merge feito, então essa issue pode ser fechada! 👍
